DROP SEQUENCE S_REPORT_LOG;

CREATE SEQUENCE S_REPORT_LOG
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  NOCACHE;

DROP SEQUENCE S_MESSAGES;

CREATE SEQUENCE S_MESSAGES
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  NOCYCLE
  NOCACHE;

DROP TABLE T_REPORT_LOG CASCADE CONSTRAINTS PURGE;

DROP TABLE T_MESSAGES CASCADE CONSTRAINTS PURGE;

CREATE TABLE T_REPORT_LOG
(
	REPORT_ID            NUMBER NOT NULL,
	REPORT_DATETIME      DATE DEFAULT SYSDATE NOT NULL,
	REPORT_MESSAGE       VARCHAR2(2000) NOT NULL 
);

CREATE UNIQUE INDEX XPKT_REPORT_LOG ON T_REPORT_LOG (REPORT_ID ASC);

ALTER TABLE T_REPORT_LOG ADD CONSTRAINT XPKT_REPORT_LOG PRIMARY KEY (REPORT_ID);

CREATE TABLE T_MESSAGES
(
	MSG_ID           NUMBER NOT NULL,
	MSG_DATETIME     DATE DEFAULT SYSDATE NOT NULL,
  MSG_NAME				 VARCHAR2(200) NOT NULL,
  MSG_EMAIL				 VARCHAR2(200) NOT NULL,
  MSG_PHONE				 VARCHAR2(15) NULL,
	MSG_VALUE        VARCHAR2(4000) NOT NULL
);

CREATE UNIQUE INDEX XPKT_MESSAGES ON T_MESSAGES (MSG_ID ASC);

ALTER TABLE T_MESSAGES ADD CONSTRAINT XPKT_MESSAGES PRIMARY KEY (MSG_ID);
/